### ISSUE TITLE
Fix failed pipeline

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#1315]
https://github.com/pawelru/ie_status?tab=readme-ov-file

**Comment by m7pr** [comment]
teal.slice failed becuase of noSuggests test failure - I'll take a look at this one https://github.com/insightsengineering/teal.slice/actions/runs/10336794337/job/28612924156

**Comment by m7pr** [comment]
Rerunning Scheduled GitHub action just in case https://github.com/insightsengineering/teal/actions/runs/10592427749
The las one failed because
- MultiAssayExperiment could not be installed https://github.com/insightsengineering/teal/actions/runs/10543890618/job/29212326612#step:7:7501 https://github.com/insightsengineering/teal/actions/runs/10543890618/job/29212326268#step:7:7521
https://github.com/insightsengineering/teal/actions/runs/10543890618/job/29212324626#step:9:649
- revdepcheck issue https://github.com/insightsengineering/teal/actions/runs/10543890618/job/29212324490#step:9:1000

**Comment by m7pr** [comment]
Rerunning again after fixes for teal.slice build in verdepcheck
https://github.com/insightsengineering/teal/actions/runs/10632915746
