### ISSUE TITLE
Teal reporter card template

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal#639]
We want to have a consistent styled report cards across all our modules.
We will get a better UX.
This will help to apply reporting functionality when many developers will work at the same time.

Example:

We want to start with a card name (need only for previewer titles)
Next we want to specify the card title.
...

**Comment by lcd2yyz** [comment]
@nikolas-burkoff @gogonzo Do you remember any details about this issue? Can we close it or do we need to refine it further?

**Comment by gogonzo** [comment]
@lcd2yyz I guess that was because reporter cards across all modules were not consistent. I don't remember the differences but some had more some had less. I'm not sure whether it's still the case. Someone needs to compare outputs of all reporters. 

Note: it's worth noting that reporter also displays filter-panel settings if any filter is applied. So to compare one must set some filters to see if they are sumamrized in all reporter cards.

**Comment by lcd2yyz** [comment]
Okay I will close this issue for now, as there were already a few other issues (some closed some still open) addressing various aspects of this. We can do a more thorough review when we return to [reporter enhancement](https://github.com/insightsengineering/nestdevs-tasks/issues/4) again
