### ISSUE TITLE
[BUG] attr(data, "code") is not reactive

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#722]
Our list of datasets with "code" attribute is buggy. Each dataset is reactive but code don't change when the data changes. It means that filter-panel code changes are not reflected in the "Show R code".

Possible solutions:
- data should be a formal class (can be S3) with reactive code. Should be easy to initialise. I propose to refactor teal.data classes to be something which holds data+code+keys only as all additional methods are not necessary in modules. This means that cdisc_data(...) can be passed also to the modules. Other scenario is to create a new class (e.g. module_data)
- attr(data, "code") can be a `reactive()`
- instead list or reactive datasets we can have reactive list of datasets.

**Comment by Polkas** [comment]
In my opinion data with preprocessing code which is static,  should be independent of FilterPanel.
The filter panel code could be added in the module with method like filter_panel_api$get_expr().

**Comment by donyunardi** [comment]
1. I'm trying to replicate the bug mentioned but I still see the filter-panel code when I click "Show R Code" after filtering the data. I must be missing something. 

1. If I'm not mistaken, the `attr(data, "code")` mentioned is referring to these lines that only get executed if there is a `data` argument in `module$ui` or `module$server`. https://github.com/insightsengineering/teal/blob/27eb96ab8b12938119af08ab2eb60d588e0c425b/R/module_nested_tabs.R#L99-L112
https://github.com/insightsengineering/teal/blob/27eb96ab8b12938119af08ab2eb60d588e0c425b/R/module_nested_tabs.R#L219-L232

   I skimmed through several modules in tmc, and they're not using `data` argument. All server functions are using `datasets` instead of `data` argument. Maybe this is why? Should this line 112 and 232 be updated to check if there's `datasets` argument instead of `data` argument?

**Comment by Polkas** [comment]
@donyunardi please check the filtering code in the SHOW R CODe , is should not be there. Remember to use the `26_new_chunks@main` branch for all packages so `staged.dependencies` is recommended.

Here is the reactive, and we asking for the data with brackets data[[NAME]]():
https://github.com/insightsengineering/teal/blob/27eb96ab8b12938119af08ab2eb60d588e0c425b/R/module_nested_tabs.R#L227

Here there is no reactive, so the `get_datasets_code` method is called inly once at the init step:
https://github.com/insightsengineering/teal/blob/27eb96ab8b12938119af08ab2eb60d588e0c425b/R/module_nested_tabs.R#L232

**Comment by donyunardi** [comment]
Thanks, @Polkas.
I understand about no reactivity behavior but I am probably looking at the wrong area when I click SHOW R CODE.
Let's refine this.

**Comment by donyunardi** [comment]
After installing the packages properly, I am able to reproduce it.
Since this bug is related to our quosure update, we will have to prioritize this within this increment.
Adding discussion label.
