### ISSUE TITLE
showRcode in `example_module` is static

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#963]
Something about `example_module` makes `verbatim_popup_srv` NOT update filtering code.

```
library(teal)

td <- within(teal_data(), iris <- iris)
datanames(td) <- "iris"

app <- init(
  data = td,
  modules = example_module(),
  filter = teal_slices(teal_slice("iris", "Species", selected = "virginica"))
) %>% runApp
```

https://github.com/insightsengineering/teal/assets/114988527/06982139-363b-448c-aabd-ae855f09c045

Works normally with a tmg module.
```
init(
  data = td,
  modules = list(
    teal.modules.general::tm_g_distribution(
      dist_var = teal.transform::data_extract_spec(
        dataname = "iris",
        select = teal.transform::select_spec(variable_choices("iris"), "Petal.Length")
      ),
      ggplot2_args = teal.widgets::ggplot2_args(
        labs = list(subtitle = "Plot generated by Distribution Module")
      )
    )
  ),
  filter = teal_slices(teal_slice("iris", "Species", selected = "virginica"))
) %>% runApp
```

**Comment by donyunardi** [comment]
Based on our discussion, this issue is no longer relevant in the `refactor` branch as the filtering code gets updated when the filters are changed in `example_module`.

Closing issue.

During discussion, we noticed that the filtering code was repeated twice:
![image](https://github.com/insightsengineering/teal/assets/8597300/6a219ac6-44d2-4393-850d-36ebfd7eaad9)

and if filters are removed, there are additional line breaks under `stopifnot` statement.
![image](https://github.com/insightsengineering/teal/assets/8597300/738a1a92-b0f0-4060-b409-dd140426f1da)

I'll open a new issue for the repeated code and the additional line breaks is related with https://github.com/insightsengineering/teal.gallery/issues/113
